// File generated by FlutterFire CLI.
// DO NOT EDIT. THIS FILE IS AUTO-GENERATED.
// Run `flutterfire configure` to update.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO_WEB_API_KEY',
    appId: 'TODO_WEB_APP_ID',
    messagingSenderId: 'TODO_WEB_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    authDomain: 'TODO_AUTH_DOMAIN',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
    measurementId: 'TODO_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'TODO_ANDROID_API_KEY',
    appId: 'TODO_ANDROID_APP_ID',
    messagingSenderId: 'TODO_ANDROID_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TODO_IOS_API_KEY',
    appId: 'TODO_IOS_APP_ID',
    messagingSenderId: 'TODO_IOS_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
    iosBundleId: 'com.yoichiyatai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TODO_MACOS_API_KEY',
    appId: 'TODO_MACOS_APP_ID',
    messagingSenderId: 'TODO_MACOS_MESSAGING_SENDER_ID',
    projectId: 'TODO_PROJECT_ID',
    databaseURL: 'TODO_DATABASE_URL',
    storageBucket: 'TODO_STORAGE_BUCKET',
    iosBundleId: 'com.yoichiyatai',
  );
}
